# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

env:
  global:
    - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

jobs:
  include:
    - language: go
      go: 1.14.x
      name: "Linter and License Check"
      script:
        - make lint
        - make license
    - language: go
      go: 1.14.x
      name: "Test"
      script:
        - go test -v ./...
    - language: go
      go: 1.14.x
      name: "Test the test"
      script:
        - go test -v -run ^TestMulti$ ./test